### ISSUE TITLE
命名空间建议不要使用App

### ISSUE THREAD

**Issue by tourze** [Qzm6826/yilianyun-php-sdk#1]
为了避免跟现有项目集成时产生冲突，我建议改用带有特定标识的命名空间，例如yilianyun。
另外就是你也同样使用了命名空间App，对于一些不是特别熟悉的开发者来说，可能带来一些认知混乱的问题。

**Comment by Qzm6826** [comment]
先谢谢提醒了，个人习惯了，会更正的
