### ISSUE TITLE
PHP8.1 兼容问题

### ISSUE THREAD

**Issue by wybwsk** [Qzm6826/yilianyun-php-sdk#5]
YlyOauthClient.php line 67
mt_srand((double)microtime() * 10000);

YlyRpcClient.php line 64
mt_srand((double)microtime() * 10000);

会报错。建议做兼容处理。
Implicit conversion from float 1915.6000000000001 to int loses precision

**Comment by leideqin** [comment]
遇到了同样的问题，建议处理一下。

**Comment by leideqin** [comment]
mt_srand((double)microtime() * 10000);
修改为
$seed = mt_rand();
mt_srand($seed);
